modLoader="javafml"
loaderVersion="[39,)"
license="CC BY-NC-ND 4.0"
issueTrackerURL="https://github.com/tristankechlo/ToolLeveling/issues"
showAsResourcePack=false

[[mods]]
modId="toolleveling"
version="1.18.1 - 1.3.0"
displayName="Tool Leveling"
displayURL="https://www.curseforge.com/minecraft/mc-mods/tool-leveling-plus"
logoFile="tool_leveling_banner.png"
#credits="Thanks for this example mod goes to Java"
authors="Buecher_wurm"
description='''adds the possibility to upgrade your enchantments higher than the vanilla limit'''

[[dependencies.toolleveling]]
    modId="forge"
    mandatory=true
    versionRange="[39,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.toolleveling]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.1,1.19)"
    ordering="NONE"
    side="BOTH"